name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Qt
      run: echo "Qt5_Dir=$Qt5_Dir" >> $GITHUB_ENV

    - name: Configure CMake
      env:
        Qt5_Dir: ${{ secrets.Qt5_Dir }}
      run: |
        qmake cangaroo.pro CONFIG+=release QTC_SOURCE="$GITHUB_WORKSPACE/qtcreator" QTC_BUILD="$GITHUB_WORKSPACE/qtcreator"

    - name: Build
      run: make -j4
