name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git qt5-qmake qtbase5-dev qtbase5-dev-tools libnl-3-dev libnl-route-3-dev cmake libqt5serialport5 libqt5serialport5-dev libqt5charts5 libqt5charts5-dev
    - name: Configure QMake
      run: |
        qmake cangaroo.pro CONFIG+=release QTC_SOURCE="$GITHUB_WORKSPACE/qtcreator" QTC_BUILD="$GITHUB_WORKSPACE/qtcreator"



    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-build-artifact  # A name for the artifact
        path: ./         # The path where the build artifacts are located (update as needed)
